channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal >=7.3
  - jinja2
  - matplotlib
  - graphviz
  - bcftools =1.15
  - samtools =1.15
  - bwa =0.7.17
  - pysam =0.19
  - pygments 
  - adapterremoval=2.3.2
  - vsearch=2.15.2
  - gzip
  - bzip2
  - cutadapt =3.5
  - seqtk =1.3
  - kraken2 =2.1.2
  - blast =2.13.0
  - fastx_toolkit =0.0.14
  - megahit =1.2.9
  - itsx =1.1.3
  - ncbi-genome-download =0.3.3
